### ISSUE TITLE
Redirects are not handled if node is hidden

### ISSUE THREAD

**Issue by markuspfeifenberger** [neos/redirecthandler#39] opened 2019-12-03 11:45 UTC
If a document node is hidden, the redirect handler does not perform the redirect and a 404 is triggered.

From the perspective of the user, the URL of the (hidden) page does no longer exist in the frontend and if a redirect is defined, it should do a redirect to the defined target.

**Comment by Sebobo** [comment] 2020-06-23 15:44
As we also have an issue in the NeosAdapter package I close this one as the issue is not related to this package.

**Closed by Sebobo** 2020-06-23 15:44 UTC
